apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadcliente-api-deployment
  labels:
    app: cadcliente-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cadcliente-api
  template:
    metadata:
      labels:
        app: cadcliente-api
    spec:
      containers:
      - name: cadcliente-api
        image: gcr.io/devops-learn-304501/cadcliente-api:v1
        env:
          - name: ConnectionStrings__MySql
            valueFrom:
              secretKeyRef:
                name: cadcliente-api-secret
                key: ConnectionStrings__MySql
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3