version: '3.7'
services:
  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass Redis@1234!
    ports:
      - "6379:6379"
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge